[2023-08-03T07:28:42.244+0000] {processor.py:157} INFO - Started process (PID=427) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T07:28:42.245+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T07:28:42.245+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:28:42.245+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:28:42.721+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:28:42.719+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T07:28:42.721+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:28:42.742+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.503 seconds
[2023-08-03T07:29:13.466+0000] {processor.py:157} INFO - Started process (PID=713) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T07:29:13.466+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T07:29:13.467+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:29:13.467+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:29:13.777+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:29:13.775+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T07:29:13.777+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:29:13.791+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.327 seconds
[2023-08-03T07:29:43.901+0000] {processor.py:157} INFO - Started process (PID=997) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T07:29:43.901+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T07:29:43.902+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:29:43.902+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:29:44.214+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:29:44.212+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T07:29:44.214+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:29:44.228+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.330 seconds
[2023-08-03T07:30:14.285+0000] {processor.py:157} INFO - Started process (PID=1279) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T07:30:14.286+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T07:30:14.286+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:30:14.286+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:30:14.599+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:30:14.597+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T07:30:14.599+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:30:14.613+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.332 seconds
[2023-08-03T07:30:45.105+0000] {processor.py:157} INFO - Started process (PID=1589) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T07:30:45.106+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T07:30:45.107+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:30:45.107+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:30:45.457+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:30:45.455+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T07:30:45.458+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:30:45.473+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.371 seconds
[2023-08-03T07:31:15.965+0000] {processor.py:157} INFO - Started process (PID=1900) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T07:31:15.966+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T07:31:15.966+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:31:15.966+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:31:16.335+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:31:16.333+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T07:31:16.335+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:31:16.354+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.392 seconds
[2023-08-03T07:31:47.321+0000] {processor.py:157} INFO - Started process (PID=2216) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T07:31:47.322+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T07:31:47.322+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:31:47.322+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:31:47.658+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:31:47.656+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T07:31:47.658+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:31:47.674+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.356 seconds
[2023-08-03T07:32:18.181+0000] {processor.py:157} INFO - Started process (PID=2511) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T07:32:18.182+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T07:32:18.183+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:32:18.182+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:32:18.569+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:32:18.567+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T07:32:18.569+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:32:18.588+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.410 seconds
[2023-08-03T07:32:48.918+0000] {processor.py:157} INFO - Started process (PID=2798) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T07:32:48.919+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T07:32:48.919+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:32:48.919+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:32:49.256+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:32:49.254+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T07:32:49.256+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:32:49.271+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.355 seconds
[2023-08-03T07:33:19.377+0000] {processor.py:157} INFO - Started process (PID=3104) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T07:33:19.378+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T07:33:19.379+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:33:19.379+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:33:19.850+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:33:19.847+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T07:33:19.851+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:33:19.870+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.495 seconds
[2023-08-03T07:33:50.448+0000] {processor.py:157} INFO - Started process (PID=3390) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T07:33:50.453+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T07:33:50.456+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:33:50.455+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:33:50.968+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:33:50.965+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T07:33:50.968+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:33:50.991+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.550 seconds
[2023-08-03T07:34:21.065+0000] {processor.py:157} INFO - Started process (PID=3716) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T07:34:21.066+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T07:34:21.067+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:34:21.067+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:34:21.445+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:34:21.443+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T07:34:21.446+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:34:21.463+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.401 seconds
[2023-08-03T07:34:52.334+0000] {processor.py:157} INFO - Started process (PID=4023) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T07:34:52.335+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T07:34:52.336+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:34:52.336+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:34:52.704+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:34:52.702+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T07:34:52.704+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:34:52.724+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.392 seconds
[2023-08-03T07:35:23.173+0000] {processor.py:157} INFO - Started process (PID=4355) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T07:35:23.174+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T07:35:23.174+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:35:23.174+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:35:23.533+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:35:23.531+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T07:35:23.533+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:35:23.548+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.377 seconds
[2023-08-03T07:35:53.887+0000] {processor.py:157} INFO - Started process (PID=4647) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T07:35:53.888+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T07:35:53.889+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:35:53.888+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:35:54.295+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:35:54.293+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T07:35:54.295+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:35:54.312+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.427 seconds
[2023-08-03T07:36:25.017+0000] {processor.py:157} INFO - Started process (PID=4939) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T07:36:25.018+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T07:36:25.018+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:36:25.018+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:36:25.370+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:36:25.368+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T07:36:25.370+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:36:25.386+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.372 seconds
[2023-08-03T07:36:55.735+0000] {processor.py:157} INFO - Started process (PID=5222) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T07:36:55.735+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T07:36:55.736+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:36:55.736+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:36:56.143+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:36:56.141+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T07:36:56.143+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:36:56.159+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.427 seconds
[2023-08-03T07:37:26.218+0000] {processor.py:157} INFO - Started process (PID=5498) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T07:37:26.219+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T07:37:26.219+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:37:26.219+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:37:26.575+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:37:26.573+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T07:37:26.575+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:37:26.591+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.375 seconds
[2023-08-03T07:37:56.730+0000] {processor.py:157} INFO - Started process (PID=5780) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T07:37:56.731+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T07:37:56.731+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:37:56.731+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:37:57.068+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:37:57.066+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T07:37:57.068+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:37:57.083+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.355 seconds
[2023-08-03T07:38:27.634+0000] {processor.py:157} INFO - Started process (PID=6064) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T07:38:27.635+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T07:38:27.636+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:38:27.636+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:38:27.948+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:38:27.946+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T07:38:27.948+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:38:27.964+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.332 seconds
[2023-08-03T07:38:58.218+0000] {processor.py:157} INFO - Started process (PID=6346) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T07:38:58.219+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T07:38:58.220+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:38:58.220+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:38:58.533+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:38:58.532+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T07:38:58.534+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:38:58.548+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.333 seconds
[2023-08-03T07:39:29.319+0000] {processor.py:157} INFO - Started process (PID=6632) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T07:39:29.320+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T07:39:29.320+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:39:29.320+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:39:29.634+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:39:29.633+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T07:39:29.634+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:39:29.649+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.332 seconds
[2023-08-03T07:40:00.098+0000] {processor.py:157} INFO - Started process (PID=6914) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T07:40:00.100+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T07:40:00.100+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:40:00.100+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:40:00.462+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:40:00.460+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T07:40:00.463+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:40:00.481+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.388 seconds
[2023-08-03T07:40:30.637+0000] {processor.py:157} INFO - Started process (PID=7198) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T07:40:30.638+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T07:40:30.638+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:40:30.638+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:40:30.945+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:40:30.944+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T07:40:30.946+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:40:30.960+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.325 seconds
[2023-08-03T07:41:01.325+0000] {processor.py:157} INFO - Started process (PID=7489) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T07:41:01.326+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T07:41:01.327+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:41:01.326+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:41:01.636+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:41:01.634+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T07:41:01.636+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:41:01.651+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.328 seconds
[2023-08-03T07:41:32.492+0000] {processor.py:157} INFO - Started process (PID=7775) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T07:41:32.493+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T07:41:32.493+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:41:32.493+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:41:32.828+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:41:32.827+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T07:41:32.828+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:41:32.844+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.354 seconds
[2023-08-03T07:42:03.777+0000] {processor.py:157} INFO - Started process (PID=8059) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T07:42:03.778+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T07:42:03.779+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:42:03.779+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:42:04.168+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:42:04.167+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T07:42:04.168+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:42:04.183+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.408 seconds
[2023-08-03T07:42:34.791+0000] {processor.py:157} INFO - Started process (PID=8341) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T07:42:34.791+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T07:42:34.792+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:42:34.792+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:42:35.110+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:42:35.109+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T07:42:35.111+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:42:35.125+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.338 seconds
[2023-08-03T07:43:06.123+0000] {processor.py:157} INFO - Started process (PID=8627) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T07:43:06.124+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T07:43:06.125+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:43:06.125+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:43:06.434+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:43:06.433+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T07:43:06.435+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:43:06.449+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.328 seconds
[2023-08-03T07:43:37.493+0000] {processor.py:157} INFO - Started process (PID=8909) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T07:43:37.494+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T07:43:37.495+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:43:37.495+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:43:37.850+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:43:37.849+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T07:43:37.851+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:43:37.867+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.377 seconds
[2023-08-03T07:44:08.372+0000] {processor.py:157} INFO - Started process (PID=9193) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T07:44:08.373+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T07:44:08.374+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:44:08.374+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:44:08.714+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:44:08.712+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T07:44:08.715+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:44:08.730+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.362 seconds
[2023-08-03T07:44:39.091+0000] {processor.py:157} INFO - Started process (PID=9519) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T07:44:39.092+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T07:44:39.092+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:44:39.092+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:44:39.475+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:44:39.473+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T07:44:39.476+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:44:39.494+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.406 seconds
[2023-08-03T07:45:10.177+0000] {processor.py:157} INFO - Started process (PID=9841) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T07:45:10.178+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T07:45:10.179+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:45:10.179+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:45:10.540+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:45:10.539+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T07:45:10.541+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:45:10.556+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.381 seconds
[2023-08-03T07:45:41.857+0000] {processor.py:157} INFO - Started process (PID=10152) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T07:45:41.858+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T07:45:41.859+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:45:41.858+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:45:42.324+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:45:42.323+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T07:45:42.325+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:45:42.337+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.485 seconds
[2023-08-03T07:46:13.165+0000] {processor.py:157} INFO - Started process (PID=10459) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T07:46:13.166+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T07:46:13.167+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:46:13.166+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:46:13.513+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:46:13.511+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T07:46:13.513+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:46:13.527+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.364 seconds
[2023-08-03T07:46:44.284+0000] {processor.py:157} INFO - Started process (PID=10743) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T07:46:44.284+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T07:46:44.285+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:46:44.285+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:46:44.712+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:46:44.711+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T07:46:44.713+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:46:44.725+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.444 seconds
[2023-08-03T07:47:14.877+0000] {processor.py:157} INFO - Started process (PID=11027) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T07:47:14.878+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T07:47:14.879+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:47:14.879+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:47:15.368+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:47:15.366+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T07:47:15.368+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:47:15.381+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.507 seconds
[2023-08-03T07:47:46.143+0000] {processor.py:157} INFO - Started process (PID=11311) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T07:47:46.144+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T07:47:46.144+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:47:46.144+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:47:46.547+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:47:46.546+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T07:47:46.548+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:47:46.559+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.419 seconds
[2023-08-03T07:48:16.775+0000] {processor.py:157} INFO - Started process (PID=11625) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T07:48:16.776+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T07:48:16.777+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:48:16.776+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:48:17.311+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:48:17.309+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T07:48:17.311+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:48:17.323+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.551 seconds
[2023-08-03T07:48:47.371+0000] {processor.py:157} INFO - Started process (PID=11909) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T07:48:47.372+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T07:48:47.373+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:48:47.372+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:48:47.791+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:48:47.790+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T07:48:47.791+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:48:47.806+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.439 seconds
[2023-08-03T07:49:18.342+0000] {processor.py:157} INFO - Started process (PID=12191) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T07:49:18.343+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T07:49:18.344+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:49:18.344+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:49:18.783+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:49:18.782+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T07:49:18.784+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:49:18.797+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.457 seconds
[2023-08-03T07:49:49.691+0000] {processor.py:157} INFO - Started process (PID=12476) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T07:49:49.692+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T07:49:49.692+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:49:49.692+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:49:50.125+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:49:50.124+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T07:49:50.125+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:49:50.139+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.451 seconds
[2023-08-03T07:50:21.259+0000] {processor.py:157} INFO - Started process (PID=12760) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T07:50:21.261+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T07:50:21.262+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:50:21.262+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:50:21.938+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:50:21.936+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T07:50:21.938+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:50:21.959+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.704 seconds
[2023-08-03T07:50:52.005+0000] {processor.py:157} INFO - Started process (PID=13109) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T07:50:52.006+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T07:50:52.007+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:50:52.007+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:50:52.423+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:50:52.422+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T07:50:52.424+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:50:52.436+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.434 seconds
[2023-08-03T07:51:22.684+0000] {processor.py:157} INFO - Started process (PID=13456) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T07:51:22.684+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T07:51:22.685+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:51:22.685+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:51:23.126+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:51:23.124+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T07:51:23.126+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:51:23.140+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.459 seconds
[2023-08-03T07:51:53.203+0000] {processor.py:157} INFO - Started process (PID=13738) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T07:51:53.204+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T07:51:53.205+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:51:53.204+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:51:53.647+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:51:53.646+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T07:51:53.648+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:51:53.660+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.459 seconds
[2023-08-03T07:52:24.625+0000] {processor.py:157} INFO - Started process (PID=14024) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T07:52:24.627+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T07:52:24.628+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:52:24.628+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:52:25.166+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:52:25.164+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T07:52:25.166+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:52:25.200+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.578 seconds
[2023-08-03T07:52:56.802+0000] {processor.py:157} INFO - Started process (PID=14308) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T07:52:56.815+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T07:52:56.816+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:52:56.816+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:52:57.424+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:52:57.423+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T07:52:57.425+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:52:57.508+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.709 seconds
[2023-08-03T07:53:27.830+0000] {processor.py:157} INFO - Started process (PID=14650) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T07:53:27.831+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T07:53:27.831+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:53:27.831+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:53:28.251+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:53:28.250+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T07:53:28.251+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:53:28.266+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.438 seconds
[2023-08-03T07:53:58.828+0000] {processor.py:157} INFO - Started process (PID=14934) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T07:53:58.829+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T07:53:58.829+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:53:58.829+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:53:59.228+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:53:59.227+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T07:53:59.228+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:53:59.240+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.415 seconds
[2023-08-03T07:54:30.063+0000] {processor.py:157} INFO - Started process (PID=15233) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T07:54:30.064+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T07:54:30.064+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:54:30.064+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:54:30.504+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:54:30.503+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T07:54:30.504+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:54:30.516+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.455 seconds
[2023-08-03T07:55:00.796+0000] {processor.py:157} INFO - Started process (PID=15531) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T07:55:00.797+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T07:55:00.797+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:55:00.797+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:55:01.238+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:55:01.237+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T07:55:01.238+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:55:01.251+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.459 seconds
[2023-08-03T07:55:31.521+0000] {processor.py:157} INFO - Started process (PID=15823) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T07:55:31.522+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T07:55:31.522+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:55:31.522+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:55:31.985+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:55:31.984+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T07:55:31.986+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:55:31.999+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.482 seconds
[2023-08-03T07:56:02.433+0000] {processor.py:157} INFO - Started process (PID=16105) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T07:56:02.434+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T07:56:02.435+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:56:02.434+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:56:03.005+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:56:03.004+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T07:56:03.005+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:56:03.021+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.594 seconds
[2023-08-03T07:56:33.625+0000] {processor.py:157} INFO - Started process (PID=16412) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T07:56:33.626+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T07:56:33.626+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:56:33.626+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:56:34.070+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:56:34.069+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T07:56:34.070+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:56:34.083+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.461 seconds
[2023-08-03T07:57:04.133+0000] {processor.py:157} INFO - Started process (PID=16710) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T07:57:04.134+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T07:57:04.135+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:57:04.135+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:57:04.624+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:57:04.623+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T07:57:04.624+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:57:04.637+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.508 seconds
[2023-08-03T07:57:34.884+0000] {processor.py:157} INFO - Started process (PID=17008) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T07:57:34.885+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T07:57:34.886+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:57:34.886+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:57:35.381+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:57:35.380+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T07:57:35.382+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:57:35.396+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.516 seconds
[2023-08-03T07:58:05.789+0000] {processor.py:157} INFO - Started process (PID=17292) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T07:58:05.790+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T07:58:05.790+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:58:05.790+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:58:06.262+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:58:06.261+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T07:58:06.263+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:58:06.279+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.493 seconds
[2023-08-03T07:58:36.630+0000] {processor.py:157} INFO - Started process (PID=17576) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T07:58:36.630+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T07:58:36.631+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:58:36.631+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:58:37.062+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:58:37.061+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T07:58:37.062+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:58:37.078+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.451 seconds
[2023-08-03T07:59:07.326+0000] {processor.py:157} INFO - Started process (PID=17875) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T07:59:07.326+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T07:59:07.327+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:59:07.327+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:59:07.770+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:59:07.768+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T07:59:07.770+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:59:07.788+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.466 seconds
[2023-08-03T07:59:38.304+0000] {processor.py:157} INFO - Started process (PID=18183) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T07:59:38.305+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T07:59:38.306+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:59:38.306+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:59:38.769+0000] {logging_mixin.py:150} INFO - [2023-08-03T07:59:38.768+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T07:59:38.769+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T07:59:38.781+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.479 seconds
[2023-08-03T08:00:08.822+0000] {processor.py:157} INFO - Started process (PID=18463) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T08:00:08.823+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T08:00:08.824+0000] {logging_mixin.py:150} INFO - [2023-08-03T08:00:08.824+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T08:00:09.260+0000] {logging_mixin.py:150} INFO - [2023-08-03T08:00:09.259+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T08:00:09.261+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T08:00:09.273+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.455 seconds
[2023-08-03T08:00:39.525+0000] {processor.py:157} INFO - Started process (PID=18741) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T08:00:39.526+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T08:00:39.527+0000] {logging_mixin.py:150} INFO - [2023-08-03T08:00:39.526+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T08:00:40.006+0000] {logging_mixin.py:150} INFO - [2023-08-03T08:00:40.005+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T08:00:40.007+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T08:00:40.022+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.500 seconds
[2023-08-03T08:01:10.420+0000] {processor.py:157} INFO - Started process (PID=19043) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T08:01:10.421+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T08:01:10.422+0000] {logging_mixin.py:150} INFO - [2023-08-03T08:01:10.421+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T08:01:10.872+0000] {logging_mixin.py:150} INFO - [2023-08-03T08:01:10.871+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T08:01:10.872+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T08:01:10.885+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.468 seconds
[2023-08-03T08:01:41.211+0000] {processor.py:157} INFO - Started process (PID=19329) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T08:01:41.212+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T08:01:41.212+0000] {logging_mixin.py:150} INFO - [2023-08-03T08:01:41.212+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T08:01:41.674+0000] {logging_mixin.py:150} INFO - [2023-08-03T08:01:41.672+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T08:01:41.674+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T08:01:41.691+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.482 seconds
[2023-08-03T08:02:11.949+0000] {processor.py:157} INFO - Started process (PID=19612) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T08:02:11.950+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T08:02:11.951+0000] {logging_mixin.py:150} INFO - [2023-08-03T08:02:11.950+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T08:02:12.402+0000] {logging_mixin.py:150} INFO - [2023-08-03T08:02:12.401+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T08:02:12.402+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T08:02:12.418+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.471 seconds
[2023-08-03T08:02:42.998+0000] {processor.py:157} INFO - Started process (PID=19896) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T08:02:42.998+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T08:02:42.999+0000] {logging_mixin.py:150} INFO - [2023-08-03T08:02:42.999+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T08:02:43.480+0000] {logging_mixin.py:150} INFO - [2023-08-03T08:02:43.479+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T08:02:43.481+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T08:02:43.508+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.513 seconds
[2023-08-03T08:03:14.411+0000] {processor.py:157} INFO - Started process (PID=20212) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T08:03:14.412+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T08:03:14.413+0000] {logging_mixin.py:150} INFO - [2023-08-03T08:03:14.412+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T08:03:14.865+0000] {logging_mixin.py:150} INFO - [2023-08-03T08:03:14.864+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T08:03:14.866+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T08:03:14.879+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.471 seconds
[2023-08-03T08:03:45.659+0000] {processor.py:157} INFO - Started process (PID=20501) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T08:03:45.659+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T08:03:45.660+0000] {logging_mixin.py:150} INFO - [2023-08-03T08:03:45.660+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T08:03:46.058+0000] {logging_mixin.py:150} INFO - [2023-08-03T08:03:46.057+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T08:03:46.058+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T08:03:46.074+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.417 seconds
[2023-08-03T08:04:16.455+0000] {processor.py:157} INFO - Started process (PID=20795) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T08:04:16.456+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T08:04:16.457+0000] {logging_mixin.py:150} INFO - [2023-08-03T08:04:16.456+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T08:04:16.886+0000] {logging_mixin.py:150} INFO - [2023-08-03T08:04:16.884+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T08:04:16.886+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T08:04:16.899+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.447 seconds
[2023-08-03T08:04:47.550+0000] {processor.py:157} INFO - Started process (PID=21079) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T08:04:47.551+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T08:04:47.552+0000] {logging_mixin.py:150} INFO - [2023-08-03T08:04:47.552+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T08:04:48.025+0000] {logging_mixin.py:150} INFO - [2023-08-03T08:04:48.024+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T08:04:48.025+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T08:04:48.040+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.492 seconds
[2023-08-03T08:05:18.569+0000] {processor.py:157} INFO - Started process (PID=21371) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T08:05:18.569+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T08:05:18.570+0000] {logging_mixin.py:150} INFO - [2023-08-03T08:05:18.570+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T08:05:18.957+0000] {logging_mixin.py:150} INFO - [2023-08-03T08:05:18.956+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T08:05:18.957+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T08:05:18.969+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.403 seconds
[2023-08-03T08:05:49.557+0000] {processor.py:157} INFO - Started process (PID=21673) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T08:05:49.557+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T08:05:49.558+0000] {logging_mixin.py:150} INFO - [2023-08-03T08:05:49.558+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T08:05:49.944+0000] {logging_mixin.py:150} INFO - [2023-08-03T08:05:49.943+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T08:05:49.944+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T08:05:49.956+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.402 seconds
[2023-08-03T08:06:20.389+0000] {processor.py:157} INFO - Started process (PID=21960) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T08:06:20.390+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T08:06:20.391+0000] {logging_mixin.py:150} INFO - [2023-08-03T08:06:20.390+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T08:06:20.812+0000] {logging_mixin.py:150} INFO - [2023-08-03T08:06:20.811+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T08:06:20.813+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T08:06:20.827+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.440 seconds
[2023-08-03T08:06:51.055+0000] {processor.py:157} INFO - Started process (PID=22244) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T08:06:51.056+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T08:06:51.056+0000] {logging_mixin.py:150} INFO - [2023-08-03T08:06:51.056+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T08:06:51.444+0000] {logging_mixin.py:150} INFO - [2023-08-03T08:06:51.443+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T08:06:51.444+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T08:06:51.456+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.404 seconds
[2023-08-03T08:07:22.141+0000] {processor.py:157} INFO - Started process (PID=22528) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T08:07:22.142+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T08:07:22.143+0000] {logging_mixin.py:150} INFO - [2023-08-03T08:07:22.143+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T08:07:22.523+0000] {logging_mixin.py:150} INFO - [2023-08-03T08:07:22.522+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T08:07:22.524+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T08:07:22.536+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.398 seconds
[2023-08-03T08:07:53.540+0000] {processor.py:157} INFO - Started process (PID=22812) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T08:07:53.541+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T08:07:53.541+0000] {logging_mixin.py:150} INFO - [2023-08-03T08:07:53.541+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T08:07:53.919+0000] {logging_mixin.py:150} INFO - [2023-08-03T08:07:53.918+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T08:07:53.920+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T08:07:53.932+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.394 seconds
[2023-08-03T08:08:25.209+0000] {processor.py:157} INFO - Started process (PID=23129) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T08:08:25.210+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T08:08:25.211+0000] {logging_mixin.py:150} INFO - [2023-08-03T08:08:25.210+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T08:08:25.620+0000] {logging_mixin.py:150} INFO - [2023-08-03T08:08:25.618+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T08:08:25.620+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T08:08:25.633+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.427 seconds
[2023-08-03T08:08:56.603+0000] {processor.py:157} INFO - Started process (PID=23428) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T08:08:56.604+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T08:08:56.604+0000] {logging_mixin.py:150} INFO - [2023-08-03T08:08:56.604+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T08:08:57.079+0000] {logging_mixin.py:150} INFO - [2023-08-03T08:08:57.078+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T08:08:57.079+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T08:08:57.092+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.491 seconds
[2023-08-03T08:09:27.959+0000] {processor.py:157} INFO - Started process (PID=23727) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T08:09:27.960+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T08:09:27.961+0000] {logging_mixin.py:150} INFO - [2023-08-03T08:09:27.960+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T08:09:28.373+0000] {logging_mixin.py:150} INFO - [2023-08-03T08:09:28.372+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T08:09:28.373+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T08:09:28.386+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.429 seconds
[2023-08-03T08:09:58.623+0000] {processor.py:157} INFO - Started process (PID=24025) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T08:09:58.626+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T08:09:58.627+0000] {logging_mixin.py:150} INFO - [2023-08-03T08:09:58.627+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T08:09:59.175+0000] {logging_mixin.py:150} INFO - [2023-08-03T08:09:59.174+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T08:09:59.175+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T08:09:59.189+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.569 seconds
[2023-08-03T08:10:29.833+0000] {processor.py:157} INFO - Started process (PID=24315) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T08:10:29.835+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T08:10:29.835+0000] {logging_mixin.py:150} INFO - [2023-08-03T08:10:29.835+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T08:10:30.375+0000] {logging_mixin.py:150} INFO - [2023-08-03T08:10:30.374+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T08:10:30.375+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T08:10:30.392+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.561 seconds
[2023-08-03T08:11:00.948+0000] {processor.py:157} INFO - Started process (PID=24649) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T08:11:00.949+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T08:11:00.949+0000] {logging_mixin.py:150} INFO - [2023-08-03T08:11:00.949+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T08:11:01.394+0000] {logging_mixin.py:150} INFO - [2023-08-03T08:11:01.392+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T08:11:01.395+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T08:11:01.411+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.466 seconds
[2023-08-03T08:11:31.685+0000] {processor.py:157} INFO - Started process (PID=24961) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T08:11:31.685+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T08:11:31.686+0000] {logging_mixin.py:150} INFO - [2023-08-03T08:11:31.686+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T08:11:32.123+0000] {logging_mixin.py:150} INFO - [2023-08-03T08:11:32.122+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T08:11:32.123+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T08:11:32.135+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.454 seconds
[2023-08-03T08:12:02.969+0000] {processor.py:157} INFO - Started process (PID=25284) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T08:12:02.970+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T08:12:02.971+0000] {logging_mixin.py:150} INFO - [2023-08-03T08:12:02.971+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T08:12:03.421+0000] {logging_mixin.py:150} INFO - [2023-08-03T08:12:03.419+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T08:12:03.421+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T08:12:03.436+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.469 seconds
[2023-08-03T08:12:33.616+0000] {processor.py:157} INFO - Started process (PID=25604) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T08:12:33.616+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T08:12:33.617+0000] {logging_mixin.py:150} INFO - [2023-08-03T08:12:33.617+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T08:12:34.076+0000] {logging_mixin.py:150} INFO - [2023-08-03T08:12:34.075+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T08:12:34.077+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T08:12:34.090+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.477 seconds
[2023-08-03T08:13:05.272+0000] {processor.py:157} INFO - Started process (PID=25923) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T08:13:05.273+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T08:13:05.274+0000] {logging_mixin.py:150} INFO - [2023-08-03T08:13:05.274+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T08:13:05.717+0000] {logging_mixin.py:150} INFO - [2023-08-03T08:13:05.716+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T08:13:05.717+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T08:13:05.732+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.464 seconds
[2023-08-03T08:13:36.126+0000] {processor.py:157} INFO - Started process (PID=26212) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T08:13:36.127+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T08:13:36.127+0000] {logging_mixin.py:150} INFO - [2023-08-03T08:13:36.127+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T08:13:36.592+0000] {logging_mixin.py:150} INFO - [2023-08-03T08:13:36.591+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T08:13:36.592+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T08:13:36.606+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.483 seconds
[2023-08-03T08:14:06.762+0000] {processor.py:157} INFO - Started process (PID=26516) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T08:14:06.763+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T08:14:06.763+0000] {logging_mixin.py:150} INFO - [2023-08-03T08:14:06.763+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T08:14:07.192+0000] {logging_mixin.py:150} INFO - [2023-08-03T08:14:07.191+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T08:14:07.192+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T08:14:07.205+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.446 seconds
[2023-08-03T08:14:37.658+0000] {processor.py:157} INFO - Started process (PID=26798) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T08:14:37.660+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T08:14:37.662+0000] {logging_mixin.py:150} INFO - [2023-08-03T08:14:37.661+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T08:14:38.140+0000] {logging_mixin.py:150} INFO - [2023-08-03T08:14:38.139+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T08:14:38.140+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T08:14:38.154+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.500 seconds
[2023-08-03T08:15:08.675+0000] {processor.py:157} INFO - Started process (PID=27083) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T08:15:08.675+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T08:15:08.676+0000] {logging_mixin.py:150} INFO - [2023-08-03T08:15:08.676+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T08:15:09.154+0000] {logging_mixin.py:150} INFO - [2023-08-03T08:15:09.153+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T08:15:09.154+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T08:15:09.168+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.496 seconds
[2023-08-03T08:15:39.234+0000] {processor.py:157} INFO - Started process (PID=27359) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T08:15:39.235+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T08:15:39.236+0000] {logging_mixin.py:150} INFO - [2023-08-03T08:15:39.235+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T08:15:39.719+0000] {logging_mixin.py:150} INFO - [2023-08-03T08:15:39.717+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T08:15:39.720+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T08:15:39.734+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.504 seconds
[2023-08-03T08:16:10.481+0000] {processor.py:157} INFO - Started process (PID=27652) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T08:16:10.482+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T08:16:10.483+0000] {logging_mixin.py:150} INFO - [2023-08-03T08:16:10.482+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T08:16:10.907+0000] {logging_mixin.py:150} INFO - [2023-08-03T08:16:10.906+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T08:16:10.908+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T08:16:10.921+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.443 seconds
[2023-08-03T08:16:41.152+0000] {processor.py:157} INFO - Started process (PID=27946) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T08:16:41.152+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T08:16:41.153+0000] {logging_mixin.py:150} INFO - [2023-08-03T08:16:41.153+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T08:16:41.551+0000] {logging_mixin.py:150} INFO - [2023-08-03T08:16:41.550+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T08:16:41.551+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T08:16:41.564+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.415 seconds
[2023-08-03T08:17:12.175+0000] {processor.py:157} INFO - Started process (PID=28236) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T08:17:12.176+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T08:17:12.177+0000] {logging_mixin.py:150} INFO - [2023-08-03T08:17:12.176+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T08:17:12.613+0000] {logging_mixin.py:150} INFO - [2023-08-03T08:17:12.612+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T08:17:12.613+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T08:17:12.627+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.454 seconds
[2023-08-03T08:17:42.735+0000] {processor.py:157} INFO - Started process (PID=28518) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T08:17:42.736+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T08:17:42.737+0000] {logging_mixin.py:150} INFO - [2023-08-03T08:17:42.736+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T08:17:43.184+0000] {logging_mixin.py:150} INFO - [2023-08-03T08:17:43.183+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T08:17:43.184+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T08:17:43.197+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.466 seconds
[2023-08-03T08:18:14.007+0000] {processor.py:157} INFO - Started process (PID=28814) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T08:18:14.007+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T08:18:14.008+0000] {logging_mixin.py:150} INFO - [2023-08-03T08:18:14.008+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T08:18:14.499+0000] {logging_mixin.py:150} INFO - [2023-08-03T08:18:14.498+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T08:18:14.499+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T08:18:14.516+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.512 seconds
[2023-08-03T08:18:44.588+0000] {processor.py:157} INFO - Started process (PID=29131) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T08:18:44.589+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T08:18:44.590+0000] {logging_mixin.py:150} INFO - [2023-08-03T08:18:44.590+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T08:18:45.046+0000] {logging_mixin.py:150} INFO - [2023-08-03T08:18:45.045+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T08:18:45.046+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T08:18:45.061+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.476 seconds
[2023-08-03T08:19:15.995+0000] {processor.py:157} INFO - Started process (PID=29420) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T08:19:15.996+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T08:19:15.997+0000] {logging_mixin.py:150} INFO - [2023-08-03T08:19:15.996+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T08:19:16.466+0000] {logging_mixin.py:150} INFO - [2023-08-03T08:19:16.465+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T08:19:16.466+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T08:19:16.481+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.489 seconds
[2023-08-03T08:19:47.020+0000] {processor.py:157} INFO - Started process (PID=29703) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T08:19:47.021+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T08:19:47.022+0000] {logging_mixin.py:150} INFO - [2023-08-03T08:19:47.021+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T08:19:47.491+0000] {logging_mixin.py:150} INFO - [2023-08-03T08:19:47.489+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T08:19:47.491+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T08:19:47.505+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.488 seconds
[2023-08-03T08:20:18.110+0000] {processor.py:157} INFO - Started process (PID=29987) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T08:20:18.111+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T08:20:18.112+0000] {logging_mixin.py:150} INFO - [2023-08-03T08:20:18.112+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T08:20:18.629+0000] {logging_mixin.py:150} INFO - [2023-08-03T08:20:18.628+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T08:20:18.629+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T08:20:18.648+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.540 seconds
[2023-08-03T08:20:49.445+0000] {processor.py:157} INFO - Started process (PID=30271) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T08:20:49.445+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T08:20:49.446+0000] {logging_mixin.py:150} INFO - [2023-08-03T08:20:49.446+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T08:20:49.929+0000] {logging_mixin.py:150} INFO - [2023-08-03T08:20:49.928+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T08:20:49.930+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T08:20:49.946+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.504 seconds
[2023-08-03T08:21:20.998+0000] {processor.py:157} INFO - Started process (PID=30558) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T08:21:20.999+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T08:21:21.000+0000] {logging_mixin.py:150} INFO - [2023-08-03T08:21:20.999+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T08:21:21.458+0000] {logging_mixin.py:150} INFO - [2023-08-03T08:21:21.457+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T08:21:21.458+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T08:21:21.473+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.479 seconds
[2023-08-03T08:21:52.367+0000] {processor.py:157} INFO - Started process (PID=30845) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T08:21:52.368+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T08:21:52.369+0000] {logging_mixin.py:150} INFO - [2023-08-03T08:21:52.369+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T08:21:52.859+0000] {logging_mixin.py:150} INFO - [2023-08-03T08:21:52.858+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T08:21:52.860+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T08:21:52.875+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.511 seconds
[2023-08-03T08:22:23.605+0000] {processor.py:157} INFO - Started process (PID=31129) to work on /opt/airflow/dags/hello_dag.py
[2023-08-03T08:22:23.605+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-03T08:22:23.606+0000] {logging_mixin.py:150} INFO - [2023-08-03T08:22:23.606+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-03T08:22:24.054+0000] {logging_mixin.py:150} INFO - [2023-08-03T08:22:24.053+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-03T08:22:24.054+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-03T08:22:24.068+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.467 seconds
