[2023-08-03T07:33:17.126+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: abc_data2bot_etl_dag.run_dbt_analytics manual__2023-08-03T07:30:36.306477+00:00 [queued]>
[2023-08-03T07:33:17.136+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: abc_data2bot_etl_dag.run_dbt_analytics manual__2023-08-03T07:30:36.306477+00:00 [queued]>
[2023-08-03T07:33:17.137+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 3
[2023-08-03T07:33:17.154+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): run_dbt_analytics> on 2023-08-03 07:30:36.306477+00:00
[2023-08-03T07:33:17.161+0000] {standard_task_runner.py:57} INFO - Started process 3000 to run task
[2023-08-03T07:33:17.164+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'abc_data2bot_etl_dag', 'run_dbt_analytics', 'manual__2023-08-03T07:30:36.306477+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/etl_abc_dag.py', '--cfg-path', '/tmp/tmpvqzmhw4k']
[2023-08-03T07:33:17.165+0000] {standard_task_runner.py:85} INFO - Job 10: Subtask run_dbt_analytics
[2023-08-03T07:33:17.212+0000] {task_command.py:410} INFO - Running <TaskInstance: abc_data2bot_etl_dag.run_dbt_analytics manual__2023-08-03T07:30:36.306477+00:00 [running]> on host d75389520dc6
[2023-08-03T07:33:17.369+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='idowu' AIRFLOW_CTX_DAG_ID='abc_data2bot_etl_dag' AIRFLOW_CTX_TASK_ID='run_dbt_analytics' AIRFLOW_CTX_EXECUTION_DATE='2023-08-03T07:30:36.306477+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-08-03T07:30:36.306477+00:00'
[2023-08-03T07:33:27.260+0000] {local_task_job_runner.py:292} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2023-08-03T07:33:27.264+0000] {process_utils.py:135} INFO - Sending Signals.SIGTERM to group 3000. PIDs of all processes in the group: [3016, 3017, 3000]
[2023-08-03T07:33:27.264+0000] {process_utils.py:86} INFO - Sending the signal Signals.SIGTERM to group 3000
[2023-08-03T07:33:27.264+0000] {taskinstance.py:1517} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-08-03T07:33:27.278+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=3017, status='terminated', started='07:33:17') (3017) terminated with exit code None
[2023-08-03T07:33:27.291+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=3000, status='terminated', exitcode=0, started='07:33:17') (3000) terminated with exit code 0
[2023-08-03T07:33:27.292+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=3016, status='terminated', started='07:33:17') (3016) terminated with exit code None
