[2023-08-02T17:21:04.690+0000] {processor.py:157} INFO - Started process (PID=427) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T17:21:04.691+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T17:21:04.692+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:21:04.692+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:21:05.079+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:21:05.077+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T17:21:05.079+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:21:05.096+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.409 seconds
[2023-08-02T17:21:35.495+0000] {processor.py:157} INFO - Started process (PID=712) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T17:21:35.496+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T17:21:35.497+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:21:35.497+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:21:35.858+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:21:35.855+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T17:21:35.858+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:21:35.875+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.382 seconds
[2023-08-02T17:22:09.095+0000] {processor.py:157} INFO - Started process (PID=1038) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T17:22:09.111+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T17:22:09.112+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:22:09.112+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:22:09.868+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:22:09.865+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T17:22:09.868+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:22:09.889+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.797 seconds
[2023-08-02T17:22:40.731+0000] {processor.py:157} INFO - Started process (PID=1340) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T17:22:40.732+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T17:22:40.733+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:22:40.733+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:22:41.233+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:22:41.231+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T17:22:41.233+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:22:41.250+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.523 seconds
[2023-08-02T17:23:11.763+0000] {processor.py:157} INFO - Started process (PID=1650) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T17:23:11.764+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T17:23:11.765+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:23:11.765+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:23:12.123+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:23:12.122+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T17:23:12.123+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:23:12.141+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.381 seconds
[2023-08-02T17:23:42.871+0000] {processor.py:157} INFO - Started process (PID=1934) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T17:23:42.872+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T17:23:42.873+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:23:42.873+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:23:43.278+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:23:43.276+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T17:23:43.278+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:23:43.294+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.428 seconds
[2023-08-02T17:24:13.428+0000] {processor.py:157} INFO - Started process (PID=2238) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T17:24:13.429+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T17:24:13.430+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:24:13.430+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:24:13.825+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:24:13.823+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T17:24:13.825+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:24:13.842+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.416 seconds
[2023-08-02T17:24:43.928+0000] {processor.py:157} INFO - Started process (PID=2514) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T17:24:43.928+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T17:24:43.929+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:24:43.929+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:24:44.356+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:24:44.354+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T17:24:44.356+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:24:44.376+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.452 seconds
[2023-08-02T17:25:14.675+0000] {processor.py:157} INFO - Started process (PID=2798) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T17:25:14.676+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T17:25:14.676+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:25:14.676+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:25:15.109+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:25:15.107+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T17:25:15.110+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:25:15.129+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.458 seconds
[2023-08-02T17:25:45.565+0000] {processor.py:157} INFO - Started process (PID=3082) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T17:25:45.566+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T17:25:45.568+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:25:45.568+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:25:46.081+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:25:46.079+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T17:25:46.081+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:25:46.098+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.539 seconds
[2023-08-02T17:26:16.417+0000] {processor.py:157} INFO - Started process (PID=3386) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T17:26:16.419+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T17:26:16.420+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:26:16.420+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:26:16.914+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:26:16.911+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T17:26:16.915+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:26:16.940+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.527 seconds
[2023-08-02T17:33:14.206+0000] {processor.py:157} INFO - Started process (PID=426) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T17:33:14.209+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T17:33:14.210+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:33:14.210+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:33:14.881+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:33:14.877+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T17:33:14.882+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:33:14.910+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.711 seconds
[2023-08-02T17:33:45.444+0000] {processor.py:157} INFO - Started process (PID=703) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T17:33:45.444+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T17:33:45.445+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:33:45.445+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:33:45.866+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:33:45.864+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T17:33:45.866+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:33:45.883+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.443 seconds
[2023-08-02T17:34:15.995+0000] {processor.py:157} INFO - Started process (PID=997) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T17:34:16.002+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T17:34:16.003+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:34:16.003+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:34:16.472+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:34:16.470+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T17:34:16.472+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:34:16.500+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.509 seconds
[2023-08-02T17:34:46.976+0000] {processor.py:157} INFO - Started process (PID=1289) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T17:34:46.977+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T17:34:46.978+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:34:46.978+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:34:47.423+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:34:47.421+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T17:34:47.424+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:34:47.442+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.471 seconds
[2023-08-02T17:35:18.336+0000] {processor.py:157} INFO - Started process (PID=1572) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T17:35:18.337+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T17:35:18.338+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:35:18.338+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:35:18.859+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:35:18.857+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T17:35:18.860+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:35:18.879+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.547 seconds
[2023-08-02T17:35:49.322+0000] {processor.py:157} INFO - Started process (PID=1856) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T17:35:49.323+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T17:35:49.324+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:35:49.323+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:35:49.833+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:35:49.831+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T17:35:49.833+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:35:49.857+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.542 seconds
[2023-08-02T17:36:20.195+0000] {processor.py:157} INFO - Started process (PID=2141) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T17:36:20.196+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T17:36:20.197+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:36:20.197+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:36:20.535+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:36:20.534+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T17:36:20.536+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:36:20.552+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.359 seconds
[2023-08-02T17:36:50.766+0000] {processor.py:157} INFO - Started process (PID=2434) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T17:36:50.766+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T17:36:50.767+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:36:50.767+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:36:51.214+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:36:51.212+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T17:36:51.214+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:36:51.229+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.466 seconds
[2023-08-02T17:37:21.653+0000] {processor.py:157} INFO - Started process (PID=2719) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T17:37:21.654+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T17:37:21.654+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:37:21.654+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:37:21.974+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:37:21.972+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T17:37:21.974+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:37:21.989+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.339 seconds
[2023-08-02T17:37:52.578+0000] {processor.py:157} INFO - Started process (PID=3003) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T17:37:52.579+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T17:37:52.579+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:37:52.579+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:37:52.900+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:37:52.899+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T17:37:52.901+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:37:52.915+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.340 seconds
[2023-08-02T17:38:23.325+0000] {processor.py:157} INFO - Started process (PID=3285) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T17:38:23.327+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T17:38:23.327+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:38:23.327+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:38:23.685+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:38:23.684+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T17:38:23.686+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:38:23.701+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.379 seconds
[2023-08-02T17:38:54.503+0000] {processor.py:157} INFO - Started process (PID=3580) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T17:38:54.504+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T17:38:54.505+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:38:54.505+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:38:54.919+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:38:54.916+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T17:38:54.919+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:38:54.943+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.443 seconds
[2023-08-02T17:39:25.697+0000] {processor.py:157} INFO - Started process (PID=3864) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T17:39:25.698+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T17:39:25.699+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:39:25.699+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:39:26.042+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:39:26.040+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T17:39:26.042+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:39:26.057+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.362 seconds
[2023-08-02T17:39:56.883+0000] {processor.py:157} INFO - Started process (PID=4147) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T17:39:56.884+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T17:39:56.885+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:39:56.885+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:39:57.217+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:39:57.215+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T17:39:57.218+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:39:57.232+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.352 seconds
[2023-08-02T17:40:27.713+0000] {processor.py:157} INFO - Started process (PID=4431) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T17:40:27.714+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T17:40:27.715+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:40:27.715+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:40:28.085+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:40:28.084+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T17:40:28.086+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:40:28.107+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.397 seconds
[2023-08-02T17:40:58.800+0000] {processor.py:157} INFO - Started process (PID=4715) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T17:40:58.801+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T17:40:58.801+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:40:58.801+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:40:59.253+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:40:59.251+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T17:40:59.254+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:40:59.277+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.480 seconds
[2023-08-02T17:41:29.336+0000] {processor.py:157} INFO - Started process (PID=5001) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T17:41:29.337+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T17:41:29.337+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:41:29.337+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:41:29.765+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:41:29.763+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T17:41:29.766+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:41:29.786+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.454 seconds
[2023-08-02T17:42:00.414+0000] {processor.py:157} INFO - Started process (PID=5284) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T17:42:00.414+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T17:42:00.415+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:42:00.415+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:42:00.796+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:42:00.794+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T17:42:00.796+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:42:00.814+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.403 seconds
[2023-08-02T17:42:30.990+0000] {processor.py:157} INFO - Started process (PID=5563) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T17:42:30.991+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T17:42:30.991+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:42:30.991+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:42:31.500+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:42:31.496+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T17:42:31.500+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:42:31.521+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.536 seconds
[2023-08-02T17:43:01.697+0000] {processor.py:157} INFO - Started process (PID=5858) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T17:43:01.698+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T17:43:01.699+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:43:01.698+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:43:02.113+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:43:02.111+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T17:43:02.113+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:43:02.128+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.435 seconds
[2023-08-02T17:43:32.172+0000] {processor.py:157} INFO - Started process (PID=6141) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T17:43:32.173+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T17:43:32.174+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:43:32.174+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:43:32.559+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:43:32.557+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T17:43:32.560+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:43:32.587+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.418 seconds
[2023-08-02T17:44:03.285+0000] {processor.py:157} INFO - Started process (PID=6433) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T17:44:03.286+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T17:44:03.287+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:44:03.286+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:44:03.616+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:44:03.614+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T17:44:03.616+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:44:03.630+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.349 seconds
[2023-08-02T17:44:34.492+0000] {processor.py:157} INFO - Started process (PID=6719) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T17:44:34.493+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T17:44:34.494+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:44:34.494+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:44:34.807+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:44:34.806+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T17:44:34.808+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:44:34.822+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.332 seconds
[2023-08-02T17:45:05.698+0000] {processor.py:157} INFO - Started process (PID=7013) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T17:45:05.698+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T17:45:05.699+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:45:05.699+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:45:06.007+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:45:06.005+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T17:45:06.007+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:45:06.021+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.326 seconds
[2023-08-02T17:45:36.307+0000] {processor.py:157} INFO - Started process (PID=7297) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T17:45:36.308+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T17:45:36.309+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:45:36.309+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:45:36.683+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:45:36.681+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T17:45:36.683+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:45:36.698+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.395 seconds
[2023-08-02T17:46:06.896+0000] {processor.py:157} INFO - Started process (PID=7608) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T17:46:06.897+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T17:46:06.898+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:46:06.898+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:46:07.228+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:46:07.227+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T17:46:07.228+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:46:07.246+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.353 seconds
[2023-08-02T17:46:37.996+0000] {processor.py:157} INFO - Started process (PID=7889) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T17:46:37.997+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T17:46:37.998+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:46:37.998+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:46:38.338+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:46:38.336+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T17:46:38.338+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:46:38.353+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.359 seconds
[2023-08-02T17:47:08.440+0000] {processor.py:157} INFO - Started process (PID=8165) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T17:47:08.441+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T17:47:08.442+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:47:08.441+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:47:08.837+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:47:08.836+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T17:47:08.838+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:47:08.852+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.415 seconds
[2023-08-02T17:47:39.650+0000] {processor.py:157} INFO - Started process (PID=8459) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T17:47:39.651+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T17:47:39.651+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:47:39.651+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:47:40.106+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:47:40.104+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T17:47:40.107+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:47:40.220+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.573 seconds
[2023-08-02T17:48:10.855+0000] {processor.py:157} INFO - Started process (PID=8768) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T17:48:10.856+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T17:48:10.856+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:48:10.856+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:48:11.183+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:48:11.181+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T17:48:11.183+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:48:11.198+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.346 seconds
[2023-08-02T17:48:41.338+0000] {processor.py:157} INFO - Started process (PID=9054) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T17:48:41.339+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T17:48:41.340+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:48:41.339+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:48:41.659+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:48:41.657+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T17:48:41.659+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:48:41.674+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.338 seconds
[2023-08-02T17:49:12.455+0000] {processor.py:157} INFO - Started process (PID=9336) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T17:49:12.456+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T17:49:12.457+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:49:12.457+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:49:12.797+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:49:12.796+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T17:49:12.798+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:49:12.817+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.365 seconds
[2023-08-02T17:49:42.901+0000] {processor.py:157} INFO - Started process (PID=9621) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T17:49:42.902+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T17:49:42.903+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:49:42.903+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:49:43.282+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:49:43.280+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T17:49:43.282+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:49:43.298+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.400 seconds
[2023-08-02T17:50:13.413+0000] {processor.py:157} INFO - Started process (PID=9907) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T17:50:13.414+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T17:50:13.415+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:50:13.415+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:50:13.917+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:50:13.914+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T17:50:13.917+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:50:13.936+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.527 seconds
[2023-08-02T17:50:44.315+0000] {processor.py:157} INFO - Started process (PID=10201) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T17:50:44.316+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T17:50:44.316+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:50:44.316+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:50:44.674+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:50:44.672+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T17:50:44.674+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:50:44.689+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.376 seconds
[2023-08-02T17:51:15.073+0000] {processor.py:157} INFO - Started process (PID=10485) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T17:51:15.073+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T17:51:15.074+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:51:15.074+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:51:15.398+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:51:15.397+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T17:51:15.399+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:51:15.413+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.343 seconds
[2023-08-02T17:51:45.730+0000] {processor.py:157} INFO - Started process (PID=10767) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T17:51:45.731+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T17:51:45.731+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:51:45.731+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:51:46.144+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:51:46.143+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T17:51:46.144+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:51:46.156+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.430 seconds
[2023-08-02T17:52:16.917+0000] {processor.py:157} INFO - Started process (PID=11053) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T17:52:16.918+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T17:52:16.919+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:52:16.919+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:52:17.314+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:52:17.313+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T17:52:17.314+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:52:17.328+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.414 seconds
[2023-08-02T17:52:48.261+0000] {processor.py:157} INFO - Started process (PID=11347) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T17:52:48.262+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T17:52:48.263+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:52:48.262+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:52:48.655+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:52:48.654+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T17:52:48.655+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:52:48.667+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.410 seconds
[2023-08-02T17:53:19.248+0000] {processor.py:157} INFO - Started process (PID=11631) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T17:53:19.249+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T17:53:19.250+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:53:19.249+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:53:19.643+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:53:19.642+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T17:53:19.643+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:53:19.655+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.409 seconds
[2023-08-02T17:53:50.158+0000] {processor.py:157} INFO - Started process (PID=11915) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T17:53:50.159+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T17:53:50.159+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:53:50.159+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:53:50.557+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:53:50.556+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T17:53:50.558+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:53:50.571+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.415 seconds
[2023-08-02T17:54:20.962+0000] {processor.py:157} INFO - Started process (PID=12199) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T17:54:20.963+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T17:54:20.964+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:54:20.964+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:54:21.357+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:54:21.356+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T17:54:21.357+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:54:21.370+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.410 seconds
[2023-08-02T17:54:51.834+0000] {processor.py:157} INFO - Started process (PID=12480) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T17:54:51.835+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T17:54:51.835+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:54:51.835+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:54:52.257+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:54:52.256+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T17:54:52.257+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:54:52.270+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.438 seconds
[2023-08-02T17:55:23.129+0000] {processor.py:157} INFO - Started process (PID=12764) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T17:55:23.130+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T17:55:23.130+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:55:23.130+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:55:23.521+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:55:23.520+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T17:55:23.521+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:55:23.534+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.407 seconds
[2023-08-02T17:55:54.441+0000] {processor.py:157} INFO - Started process (PID=13049) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T17:55:54.441+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T17:55:54.442+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:55:54.442+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:55:54.833+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:55:54.832+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T17:55:54.834+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:55:54.846+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.409 seconds
[2023-08-02T17:56:25.009+0000] {processor.py:157} INFO - Started process (PID=13331) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T17:56:25.010+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T17:56:25.011+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:56:25.010+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:56:25.513+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:56:25.512+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T17:56:25.513+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:56:25.526+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.521 seconds
[2023-08-02T17:56:55.970+0000] {processor.py:157} INFO - Started process (PID=13617) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T17:56:55.971+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T17:56:55.971+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:56:55.971+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:56:56.437+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:56:56.435+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T17:56:56.437+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:56:56.450+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.482 seconds
[2023-08-02T17:57:27.947+0000] {processor.py:157} INFO - Started process (PID=13901) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T17:57:27.948+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T17:57:27.948+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:57:27.948+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:57:28.666+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:57:28.664+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T17:57:28.667+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:57:28.708+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.766 seconds
[2023-08-02T17:57:58.833+0000] {processor.py:157} INFO - Started process (PID=14200) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T17:57:58.833+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T17:57:58.834+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:57:58.834+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:57:59.240+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:57:59.239+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T17:57:59.240+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:57:59.253+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.424 seconds
[2023-08-02T17:58:29.871+0000] {processor.py:157} INFO - Started process (PID=14484) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T17:58:29.872+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T17:58:29.873+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:58:29.873+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:58:30.368+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:58:30.367+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T17:58:30.369+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:58:30.382+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.515 seconds
[2023-08-02T17:59:00.494+0000] {processor.py:157} INFO - Started process (PID=14782) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T17:59:00.495+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T17:59:00.496+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:59:00.496+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:59:00.950+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:59:00.949+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T17:59:00.950+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:59:00.963+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.473 seconds
[2023-08-02T17:59:31.645+0000] {processor.py:157} INFO - Started process (PID=15080) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T17:59:31.646+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T17:59:31.647+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:59:31.646+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:59:32.108+0000] {logging_mixin.py:150} INFO - [2023-08-02T17:59:32.107+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T17:59:32.108+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T17:59:32.124+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.481 seconds
[2023-08-02T18:00:02.767+0000] {processor.py:157} INFO - Started process (PID=15362) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T18:00:02.768+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T18:00:02.769+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:00:02.769+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:00:03.171+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:00:03.170+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T18:00:03.172+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:00:03.185+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.421 seconds
[2023-08-02T18:00:33.290+0000] {processor.py:157} INFO - Started process (PID=15648) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T18:00:33.290+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T18:00:33.291+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:00:33.291+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:00:33.721+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:00:33.720+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T18:00:33.721+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:00:33.735+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.448 seconds
[2023-08-02T18:01:04.367+0000] {processor.py:157} INFO - Started process (PID=15961) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T18:01:04.368+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T18:01:04.369+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:01:04.368+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:01:04.800+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:01:04.799+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T18:01:04.800+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:01:04.813+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.449 seconds
[2023-08-02T18:01:35.242+0000] {processor.py:157} INFO - Started process (PID=16277) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T18:01:35.243+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T18:01:35.244+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:01:35.244+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:01:35.709+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:01:35.707+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T18:01:35.709+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:01:35.735+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.496 seconds
[2023-08-02T18:02:06.114+0000] {processor.py:157} INFO - Started process (PID=16582) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T18:02:06.115+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T18:02:06.115+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:02:06.115+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:02:06.548+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:02:06.547+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T18:02:06.548+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:02:06.562+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.451 seconds
[2023-08-02T18:02:36.897+0000] {processor.py:157} INFO - Started process (PID=16893) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T18:02:36.898+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T18:02:36.899+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:02:36.899+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:02:37.394+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:02:37.393+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T18:02:37.394+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:02:37.408+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.514 seconds
[2023-08-02T18:03:07.540+0000] {processor.py:157} INFO - Started process (PID=17189) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T18:03:07.541+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T18:03:07.542+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:03:07.542+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:03:08.008+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:03:08.006+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T18:03:08.008+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:03:08.028+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.494 seconds
[2023-08-02T18:03:38.879+0000] {processor.py:157} INFO - Started process (PID=17517) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T18:03:38.880+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T18:03:38.881+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:03:38.881+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:03:39.502+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:03:39.500+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T18:03:39.502+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:03:39.520+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.645 seconds
[2023-08-02T18:04:10.455+0000] {processor.py:157} INFO - Started process (PID=17834) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T18:04:10.455+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T18:04:10.456+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:04:10.456+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:04:10.885+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:04:10.884+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T18:04:10.886+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:04:10.899+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.447 seconds
[2023-08-02T18:04:41.989+0000] {processor.py:157} INFO - Started process (PID=18134) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T18:04:42.037+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T18:04:42.037+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:04:42.037+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:04:44.643+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:04:44.642+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T18:04:44.644+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:04:44.663+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 2.684 seconds
[2023-08-02T18:05:14.750+0000] {processor.py:157} INFO - Started process (PID=18463) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T18:05:14.750+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T18:05:14.751+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:05:14.751+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:05:15.232+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:05:15.231+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T18:05:15.232+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:05:15.249+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.502 seconds
[2023-08-02T18:05:45.639+0000] {processor.py:157} INFO - Started process (PID=18779) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T18:05:45.640+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T18:05:45.641+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:05:45.640+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:05:46.047+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:05:46.046+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T18:05:46.047+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:05:46.060+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.423 seconds
[2023-08-02T18:06:16.789+0000] {processor.py:157} INFO - Started process (PID=19067) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T18:06:16.790+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T18:06:16.790+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:06:16.790+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:06:17.194+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:06:17.193+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T18:06:17.195+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:06:17.208+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.422 seconds
[2023-08-02T18:06:47.251+0000] {processor.py:157} INFO - Started process (PID=19361) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T18:06:47.252+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T18:06:47.253+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:06:47.253+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:06:47.699+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:06:47.698+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T18:06:47.699+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:06:47.712+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.463 seconds
[2023-08-02T18:07:18.490+0000] {processor.py:157} INFO - Started process (PID=19645) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T18:07:18.491+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T18:07:18.491+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:07:18.491+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:07:18.898+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:07:18.897+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T18:07:18.899+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:07:18.911+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.424 seconds
[2023-08-02T18:07:49.009+0000] {processor.py:157} INFO - Started process (PID=19944) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T18:07:49.010+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T18:07:49.011+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:07:49.011+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:07:49.457+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:07:49.456+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T18:07:49.458+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:07:49.471+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.465 seconds
[2023-08-02T18:08:20.164+0000] {processor.py:157} INFO - Started process (PID=20247) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T18:08:20.165+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T18:08:20.165+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:08:20.165+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:08:20.627+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:08:20.626+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T18:08:20.627+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:08:20.640+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.479 seconds
[2023-08-02T18:08:51.531+0000] {processor.py:157} INFO - Started process (PID=20530) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T18:08:51.532+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T18:08:51.532+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:08:51.532+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:08:51.966+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:08:51.965+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T18:08:51.966+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:08:51.980+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.451 seconds
[2023-08-02T18:09:22.485+0000] {processor.py:157} INFO - Started process (PID=20814) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T18:09:22.485+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T18:09:22.486+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:09:22.485+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:09:22.892+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:09:22.891+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T18:09:22.892+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:09:22.906+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.424 seconds
[2023-08-02T18:09:53.151+0000] {processor.py:157} INFO - Started process (PID=21098) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T18:09:53.151+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T18:09:53.152+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:09:53.152+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:09:53.571+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:09:53.570+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T18:09:53.572+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:09:53.585+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.438 seconds
[2023-08-02T18:10:23.908+0000] {processor.py:157} INFO - Started process (PID=21393) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T18:10:23.909+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T18:10:23.909+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:10:23.909+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:10:24.341+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:10:24.340+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T18:10:24.341+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:10:24.357+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.452 seconds
[2023-08-02T18:10:54.587+0000] {processor.py:157} INFO - Started process (PID=21677) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T18:10:54.588+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T18:10:54.589+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:10:54.589+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:10:55.007+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:10:55.006+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T18:10:55.007+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:10:55.021+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.437 seconds
[2023-08-02T18:11:25.282+0000] {processor.py:157} INFO - Started process (PID=21964) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T18:11:25.283+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T18:11:25.283+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:11:25.283+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:11:25.680+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:11:25.679+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T18:11:25.680+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:11:25.692+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.413 seconds
[2023-08-02T18:11:56.095+0000] {processor.py:157} INFO - Started process (PID=22248) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T18:11:56.095+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T18:11:56.096+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:11:56.096+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:11:56.632+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:11:56.631+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T18:11:56.633+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:11:56.649+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.557 seconds
[2023-08-02T18:12:27.562+0000] {processor.py:157} INFO - Started process (PID=22544) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T18:12:27.563+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T18:12:27.563+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:12:27.563+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:12:27.965+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:12:27.964+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T18:12:27.965+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:12:27.977+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.418 seconds
[2023-08-02T18:12:58.130+0000] {processor.py:157} INFO - Started process (PID=22828) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T18:12:58.131+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T18:12:58.131+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:12:58.131+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:12:58.512+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:12:58.511+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T18:12:58.512+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:12:58.525+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.398 seconds
[2023-08-02T18:13:28.699+0000] {processor.py:157} INFO - Started process (PID=23113) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T18:13:28.699+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T18:13:28.700+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:13:28.700+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:13:29.082+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:13:29.081+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T18:13:29.082+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:13:29.095+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.399 seconds
[2023-08-02T18:13:59.391+0000] {processor.py:157} INFO - Started process (PID=23397) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T18:13:59.391+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T18:13:59.392+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:13:59.392+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:13:59.779+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:13:59.778+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T18:13:59.779+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:13:59.793+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.405 seconds
[2023-08-02T18:14:29.939+0000] {processor.py:157} INFO - Started process (PID=23681) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T18:14:29.939+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T18:14:29.940+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:14:29.940+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:14:30.322+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:14:30.321+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T18:14:30.322+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:14:30.335+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.399 seconds
[2023-08-02T18:15:00.554+0000] {processor.py:157} INFO - Started process (PID=23965) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T18:15:00.555+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T18:15:00.556+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:15:00.556+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:15:00.940+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:15:00.940+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T18:15:00.941+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:15:00.953+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.402 seconds
[2023-08-02T18:15:31.360+0000] {processor.py:157} INFO - Started process (PID=24250) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T18:15:31.361+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T18:15:31.362+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:15:31.361+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:15:31.752+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:15:31.751+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T18:15:31.752+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:15:31.764+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.406 seconds
[2023-08-02T18:16:02.147+0000] {processor.py:157} INFO - Started process (PID=24537) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T18:16:02.148+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T18:16:02.148+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:16:02.148+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:16:02.641+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:16:02.640+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T18:16:02.641+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:16:02.655+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.512 seconds
[2023-08-02T18:16:32.748+0000] {processor.py:157} INFO - Started process (PID=24822) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T18:16:32.749+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T18:16:32.750+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:16:32.749+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:16:33.162+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:16:33.161+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T18:16:33.162+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:16:33.175+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.429 seconds
[2023-08-02T18:17:03.983+0000] {processor.py:157} INFO - Started process (PID=25108) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T18:17:03.983+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T18:17:03.984+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:17:03.984+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:17:04.415+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:17:04.414+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T18:17:04.416+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:17:04.428+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.448 seconds
[2023-08-02T18:17:34.489+0000] {processor.py:157} INFO - Started process (PID=25390) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T18:17:34.490+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T18:17:34.490+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:17:34.490+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:17:35.031+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:17:35.030+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T18:17:35.031+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:17:35.046+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.560 seconds
[2023-08-02T18:18:05.558+0000] {processor.py:157} INFO - Started process (PID=25673) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T18:18:05.559+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T18:18:05.560+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:18:05.559+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:18:05.992+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:18:05.991+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T18:18:05.992+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:18:06.007+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.451 seconds
[2023-08-02T18:18:36.094+0000] {processor.py:157} INFO - Started process (PID=25950) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T18:18:36.095+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T18:18:36.096+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:18:36.096+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:18:36.589+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:18:36.588+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T18:18:36.589+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:18:36.605+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.514 seconds
[2023-08-02T18:19:07.439+0000] {processor.py:157} INFO - Started process (PID=26258) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T18:19:07.440+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T18:19:07.441+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:19:07.441+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:19:07.871+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:19:07.870+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T18:19:07.871+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:19:07.884+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.447 seconds
[2023-08-02T18:19:38.059+0000] {processor.py:157} INFO - Started process (PID=26561) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T18:19:38.060+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T18:19:38.060+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:19:38.060+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:19:38.461+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:19:38.460+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T18:19:38.461+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:19:38.474+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.418 seconds
[2023-08-02T18:20:09.013+0000] {processor.py:157} INFO - Started process (PID=26845) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T18:20:09.014+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T18:20:09.014+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:20:09.014+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:20:09.435+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:20:09.434+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T18:20:09.435+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:20:09.451+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.441 seconds
[2023-08-02T18:20:39.843+0000] {processor.py:157} INFO - Started process (PID=27127) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T18:20:39.844+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T18:20:39.844+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:20:39.844+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:20:40.242+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:20:40.241+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T18:20:40.242+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:20:40.254+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.415 seconds
[2023-08-02T18:21:11.006+0000] {processor.py:157} INFO - Started process (PID=27436) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T18:21:11.007+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T18:21:11.008+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:21:11.007+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:21:11.421+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:21:11.419+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T18:21:11.421+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:21:11.433+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.429 seconds
[2023-08-02T18:21:42.274+0000] {processor.py:157} INFO - Started process (PID=27731) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T18:21:42.274+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T18:21:42.275+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:21:42.275+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:21:42.708+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:21:42.707+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T18:21:42.708+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:21:42.724+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.456 seconds
[2023-08-02T18:22:13.019+0000] {processor.py:157} INFO - Started process (PID=28015) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T18:22:13.019+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T18:22:13.020+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:22:13.020+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:22:13.400+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:22:13.399+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T18:22:13.400+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:22:13.413+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.397 seconds
[2023-08-02T18:22:44.356+0000] {processor.py:157} INFO - Started process (PID=28299) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T18:22:44.357+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T18:22:44.358+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:22:44.358+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:22:44.743+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:22:44.742+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T18:22:44.743+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:22:44.755+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.403 seconds
[2023-08-02T18:23:15.081+0000] {processor.py:157} INFO - Started process (PID=28580) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T18:23:15.082+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T18:23:15.082+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:23:15.082+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:23:15.491+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:23:15.490+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T18:23:15.491+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:23:15.506+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.427 seconds
[2023-08-02T18:23:46.198+0000] {processor.py:157} INFO - Started process (PID=28877) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T18:23:46.199+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T18:23:46.199+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:23:46.199+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:23:46.589+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:23:46.588+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T18:23:46.589+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:23:46.602+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.407 seconds
[2023-08-02T18:24:16.780+0000] {processor.py:157} INFO - Started process (PID=29161) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T18:24:16.781+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T18:24:16.781+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:24:16.781+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:24:17.179+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:24:17.178+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T18:24:17.179+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:24:17.192+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.414 seconds
[2023-08-02T18:24:47.773+0000] {processor.py:157} INFO - Started process (PID=29445) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T18:24:47.774+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T18:24:47.774+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:24:47.774+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:24:48.161+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:24:48.160+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T18:24:48.161+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:24:48.173+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.403 seconds
[2023-08-02T18:25:19.010+0000] {processor.py:157} INFO - Started process (PID=29727) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T18:25:19.011+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T18:25:19.011+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:25:19.011+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:25:19.436+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:25:19.435+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T18:25:19.436+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:25:19.448+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.441 seconds
[2023-08-02T18:25:49.599+0000] {processor.py:157} INFO - Started process (PID=30024) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T18:25:49.599+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T18:25:49.600+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:25:49.600+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:25:49.987+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:25:49.986+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T18:25:49.987+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:25:50.000+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.404 seconds
[2023-08-02T18:26:21.050+0000] {processor.py:157} INFO - Started process (PID=30308) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T18:26:21.051+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T18:26:21.051+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:26:21.051+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:26:21.394+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:26:21.392+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T18:26:21.394+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:26:21.411+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.364 seconds
[2023-08-02T18:26:51.543+0000] {processor.py:157} INFO - Started process (PID=30590) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T18:26:51.544+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T18:26:51.544+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:26:51.544+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:26:51.887+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:26:51.885+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T18:26:51.887+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:26:51.901+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.361 seconds
[2023-08-02T18:27:22.034+0000] {processor.py:157} INFO - Started process (PID=30876) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T18:27:22.035+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T18:27:22.035+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:27:22.035+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:27:22.363+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:27:22.361+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T18:27:22.363+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:27:22.379+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.347 seconds
[2023-08-02T18:27:52.492+0000] {processor.py:157} INFO - Started process (PID=31160) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T18:27:52.493+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T18:27:52.493+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:27:52.493+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:27:52.831+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:27:52.829+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T18:27:52.831+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:27:52.850+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.360 seconds
[2023-08-02T18:28:22.908+0000] {processor.py:157} INFO - Started process (PID=31444) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T18:28:22.909+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T18:28:22.910+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:28:22.910+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:28:23.336+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:28:23.333+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T18:28:23.336+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:28:23.357+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.452 seconds
[2023-08-02T18:28:54.366+0000] {processor.py:157} INFO - Started process (PID=31728) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T18:28:54.367+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T18:28:54.367+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:28:54.367+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:28:54.726+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:28:54.724+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T18:28:54.726+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:28:54.740+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.377 seconds
[2023-08-02T18:29:24.805+0000] {processor.py:157} INFO - Started process (PID=32012) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T18:29:24.806+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T18:29:24.807+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:29:24.806+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:29:25.127+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:29:25.125+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T18:29:25.127+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:29:25.141+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.338 seconds
[2023-08-02T18:29:55.664+0000] {processor.py:157} INFO - Started process (PID=32296) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T18:29:55.665+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T18:29:55.666+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:29:55.666+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:29:56.072+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:29:56.068+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T18:29:56.072+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:29:56.093+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.433 seconds
[2023-08-02T18:30:26.648+0000] {processor.py:157} INFO - Started process (PID=32580) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T18:30:26.649+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T18:30:26.650+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:30:26.649+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:30:27.050+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:30:27.048+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T18:30:27.050+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:30:27.097+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.452 seconds
[2023-08-02T18:30:57.208+0000] {processor.py:157} INFO - Started process (PID=32864) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T18:30:57.209+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T18:30:57.209+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:30:57.209+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:30:57.522+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:30:57.521+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T18:30:57.523+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:30:57.537+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.332 seconds
[2023-08-02T18:31:27.631+0000] {processor.py:157} INFO - Started process (PID=33148) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T18:31:27.632+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T18:31:27.632+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:31:27.632+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:31:27.992+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:31:27.989+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T18:31:27.992+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:31:28.007+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.378 seconds
[2023-08-02T18:31:58.353+0000] {processor.py:157} INFO - Started process (PID=33432) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T18:31:58.354+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T18:31:58.355+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:31:58.355+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:31:58.662+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:31:58.660+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T18:31:58.662+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:31:58.677+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.326 seconds
[2023-08-02T18:32:29.063+0000] {processor.py:157} INFO - Started process (PID=33716) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T18:32:29.063+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T18:32:29.064+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:32:29.064+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:32:29.370+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:32:29.369+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T18:32:29.371+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:32:29.385+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.325 seconds
[2023-08-02T18:32:59.522+0000] {processor.py:157} INFO - Started process (PID=34000) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T18:32:59.523+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T18:32:59.524+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:32:59.524+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:32:59.868+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:32:59.866+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T18:32:59.868+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:32:59.885+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.366 seconds
[2023-08-02T18:33:30.326+0000] {processor.py:157} INFO - Started process (PID=34284) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T18:33:30.327+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T18:33:30.328+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:33:30.327+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:33:30.635+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:33:30.633+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T18:33:30.635+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:33:30.649+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.326 seconds
[2023-08-02T18:34:00.914+0000] {processor.py:157} INFO - Started process (PID=34571) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T18:34:00.915+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T18:34:00.916+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:34:00.916+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:34:01.234+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:34:01.232+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T18:34:01.234+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:34:01.248+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.337 seconds
[2023-08-02T18:34:31.534+0000] {processor.py:157} INFO - Started process (PID=34855) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T18:34:31.535+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T18:34:31.536+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:34:31.535+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:34:31.848+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:34:31.846+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T18:34:31.848+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:34:31.862+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.331 seconds
[2023-08-02T18:35:02.326+0000] {processor.py:157} INFO - Started process (PID=35138) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T18:35:02.326+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T18:35:02.327+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:35:02.327+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:35:02.653+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:35:02.651+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T18:35:02.654+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:35:02.670+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.347 seconds
[2023-08-02T18:35:32.736+0000] {processor.py:157} INFO - Started process (PID=35422) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T18:35:32.736+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T18:35:32.737+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:35:32.737+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:35:33.052+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:35:33.051+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T18:35:33.053+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:35:33.066+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.333 seconds
[2023-08-02T18:36:03.949+0000] {processor.py:157} INFO - Started process (PID=35708) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T18:36:03.950+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T18:36:03.950+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:36:03.950+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:36:04.292+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:36:04.290+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T18:36:04.292+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:36:04.306+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.359 seconds
[2023-08-02T18:36:35.150+0000] {processor.py:157} INFO - Started process (PID=35992) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T18:36:35.151+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T18:36:35.152+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:36:35.151+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:36:35.558+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:36:35.556+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T18:36:35.558+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:36:35.576+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.430 seconds
[2023-08-02T18:37:05.976+0000] {processor.py:157} INFO - Started process (PID=36276) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T18:37:05.977+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T18:37:05.977+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:37:05.977+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:37:06.362+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:37:06.361+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T18:37:06.363+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:37:06.376+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.403 seconds
[2023-08-02T18:37:36.719+0000] {processor.py:157} INFO - Started process (PID=36565) to work on /opt/airflow/dags/hello_dag.py
[2023-08-02T18:37:36.719+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/hello_dag.py for tasks to queue
[2023-08-02T18:37:36.720+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:37:36.720+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:37:37.104+0000] {logging_mixin.py:150} INFO - [2023-08-02T18:37:37.102+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/hello_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hello_dag.py", line 8, in <module>
    import swagger_client
ModuleNotFoundError: No module named 'swagger_client'
[2023-08-02T18:37:37.105+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/hello_dag.py
[2023-08-02T18:37:37.133+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hello_dag.py took 0.417 seconds
